In [1]:
import numpy as np

# softmax

In [2]:
batch_size = 3
n_features = 20
n_classes = 4

In [3]:
w = np.random.rand(n_features, n_classes)
x = np.random.rand(batch_size, n_features)
b = np.random.rand(n_classes)

In [4]:
x.shape, w.shape, b.shape

((3, 20), (20, 4), (4,))

In [5]:
pred = np.dot(x, w) + b

In [6]:
pred

array([[7.22081435, 5.75157022, 6.50522435, 6.85735158],
       [7.05403088, 6.07615041, 6.23057436, 7.21347231],
       [5.80375805, 5.49447256, 5.97403503, 6.9765979 ]])

In [7]:
pred.shape

(3, 4)

In [8]:
exp_scores = np.exp(pred)

In [9]:
exp_scores

array([[1367.60230802,  314.684395  ,  668.62566202,  950.84548882],
       [1157.51516184,  435.35004663,  508.04720416, 1357.59808917],
       [ 331.54317713,  243.34314356,  393.08860017, 1071.26759684]])

In [10]:
exp_scores.sum(1, keepdims=True).shape

(3, 1)

In [11]:
exp_scores.sum(1, keepdims=True)

array([[3301.75785386],
       [3458.5105018 ],
       [2039.2425177 ]])

In [12]:
exp_scores.sum(1, keepdims=False)

array([3301.75785386, 3458.5105018 , 2039.2425177 ])

In [13]:
softmax = exp_scores / exp_scores.sum(1, keepdims=True)

In [14]:
softmax.sum(1)

array([1., 1., 1.])

In [15]:
softmax[0]

array([0.4142043 , 0.09530814, 0.20250597, 0.28798159])

In [16]:
softmax[0].sum()

1.0

In [17]:
softmax.sum(1)

array([1., 1., 1.])

In [18]:
y = np.random.randint(n_classes, size=(batch_size))

In [19]:
y

array([2, 1, 1])

In [20]:
n_classes

4

In [21]:
range(pred.shape[0]), y

(range(0, 3), array([2, 1, 1]))

In [22]:
softmax

array([[0.4142043 , 0.09530814, 0.20250597, 0.28798159],
       [0.33468603, 0.1258779 , 0.14689769, 0.39253837],
       [0.16258153, 0.11933016, 0.19276207, 0.52532624]])

In [23]:
selected_pred = softmax[range(pred.shape[0]), y]

In [24]:
selected_pred

array([0.20250597, 0.1258779 , 0.11933016])

In [25]:
selected_pred.shape

(3,)

In [26]:
loss = - np.log(selected_pred) / batch_size

In [27]:
loss

array([0.53232864, 0.69081429, 0.70862038])

In [28]:
loss.mean()

0.6439211053529063

# sigmoid

In [29]:
data_length = 3
n_features = 20
n_classes = 1

In [30]:
w = np.random.rand(n_features, n_classes) * 0.01
x = np.random.rand(data_length, n_features)
b = np.random.rand(n_classes)

In [31]:
pred = np.dot(x, w) + b

In [32]:
pred

array([[0.73884767],
       [0.74115464],
       [0.74426028]])

In [33]:
pred.shape

(3, 1)

In [34]:
sigmoid = 1 / (1 + np.exp(-pred))

In [35]:
sigmoid

array([[0.67674382],
       [0.67724829],
       [0.67792676]])

In [36]:
sigmoid.shape

(3, 1)

In [37]:
sigmoid = sigmoid.squeeze()

In [38]:
sigmoid.shape

(3,)

In [39]:
y = np.random.randint(n_classes + 1, size=(data_length))

In [40]:
y

array([1, 0, 0])

In [41]:
loss = - (y * np.log(sigmoid) + (1 - y) * np.log(1 - sigmoid)) / batch_size

In [42]:
loss

array([0.13015416, 0.37695732, 0.37765877])

In [43]:
loss.mean()

0.2949234154797824

# grad

In [62]:
w = np.random.rand(200, 100)
x = np.random.rand(32, 200)
b = np.random.rand(100)

grad_prev = np.random.rand(32, 100)

In [63]:
(np.dot(x, w) + b).shape

(32, 100)

In [64]:
grad_prev.shape, x.shape, w.shape, b.shape

((32, 100), (32, 200), (200, 100), (100,))

In [65]:
x.T.shape

(200, 32)

In [47]:
grad_w = np.dot(x.T, grad_prev)

In [66]:
grad_w.shape, grad_w.shape == w.shape

((200, 100), True)

In [67]:
grad_x = np.dot(grad_prev, w.T)

In [68]:
grad_x.shape, grad_x.shape == x.shape

((32, 200), True)

In [69]:
b.shape

(100,)

In [70]:
grad_prev.shape

(32, 100)

In [71]:
grad_b = np.dot(np.ones((32, 1)).T, grad_prev)

In [72]:
grad_b.squeeze()

array([17.41615327, 14.4368665 , 15.3033981 , 16.90409825, 19.3221594 ,
       17.70487063, 16.66775325, 16.24437405, 16.12676911, 17.08874168,
       14.41955765, 18.59126605, 16.04363414, 17.50360585, 14.75896537,
       18.31404301, 16.16699918, 15.00701968, 15.39005301, 18.00051343,
       17.20023836, 14.68116832, 14.88702735, 14.52149563, 16.83621184,
       14.74712896, 16.70024053, 17.68567026, 16.88850878, 17.69050953,
       16.66970307, 16.12294786, 16.15654288, 16.25867044, 13.1427322 ,
       16.28635429, 18.8479048 , 14.36765749, 15.26353291, 17.608116  ,
       12.34529658, 17.9884324 , 21.10161303, 15.04212412, 14.10796609,
       14.29228497, 15.38599986, 14.60480069, 17.27883192, 17.62446788,
       17.29230726, 17.16427973, 16.34473242, 14.79471734, 17.81941575,
       14.61419579, 13.94037199, 13.99051771, 17.98167108, 15.77605909,
       14.22240317, 18.34981064, 15.51491384, 16.19772001, 16.03122299,
       19.41764456, 13.4229515 , 17.58433403, 14.92781284, 15.77

In [73]:
grad_b.shape, grad_b.shape == b.shape

((1, 100), False)

In [74]:
b.shape

(100,)

In [75]:
grad_b = grad_b.squeeze()

In [76]:
grad_b.shape, grad_b.shape == b.shape

((100,), True)

In [77]:
learning_rate = 0.1

In [78]:
w = w - learning_rate * grad_w
b = b - learning_rate * grad_b

In [79]:
grad_prev.shape

(32, 100)

In [80]:
b.shape

(100,)

In [81]:
grad_b = grad_prev.sum(0)

In [82]:
grad_b.shape, grad_b.shape == b.shape

((100,), True)